# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TranslateUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,Qt
from Extra.MyAction import MyActionLineEdit
from Extra.MyAction import MyActionLabel


class TranslateMainWindow(QtWidgets.QMainWindow):
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        # 源文字文本框
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(90, 30, 601, 111))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit.setPlaceholderText('请输入要翻译的文字、语句等(自动检测)')
        self.plainTextEdit.setFont(QtGui.QFont('KaiTi',12))

        # 源文本框字数统计标签
        self.countLabel = QtWidgets.QLabel(self.centralwidget)
        self.countLabel.setGeometry(640,153,50,30)



        # 转换按钮
        self.label = MyActionLabel(self)
        self.label.setGeometry(QtCore.QRect(350, 153, 54, 30))
        labelHtml = '''
        <img src = '../ICO/转换new.png' height = '22' weight = '12' style = "vertical-top;">'''
        self.label.setText(labelHtml)
        self.label.setCursor(Qt.Qt.PointingHandCursor)

        # 翻译按钮
        self.button = QtWidgets.QPushButton('翻译',self.centralwidget)
        self.button.setGeometry(240,153,80,30)
        self.button.setObjectName('btn')
        self.button.setStyleSheet('#btn{'
                                    'background-color:#2c7adf;color:#fff;border-radius:4px;}')
        self.button.setFont(QtGui.QFont('KaiTi',12))
        self.button.setCursor(Qt.Qt.PointingHandCursor)

        # 语种下拉框
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(420, 153, 151, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        # 译文文本框
        self.translateText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.translateText.setGeometry(QtCore.QRect(90, 200, 601, 111))
        # self.translateText.setEnabled(False)
        self.translateText.setObjectName("plainTextEdit_2")
        self.translateText.setFont(QtGui.QFont('KaiTi',12))

        # 复制按钮
        self.copybtn = MyActionLabel(self)
        self.copybtn.setGeometry(650,315,54,35)
        copyHtml = '''
        <img src = '../ICO/复制.png' height = '22' weight = '12' style = "vertical-top;">'''
        self.copybtn.setText(copyHtml)
        self.copybtn.setToolTip('复制译文')
        self.copybtn.setCursor(Qt.Qt.PointingHandCursor)

        # 分割线
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 350, 781, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)


        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "英语"))
        self.comboBox.setItemText(1, _translate("MainWindow", "日语"))
        self.comboBox.setItemText(2, _translate("MainWindow", "中文"))
